import { BEYOND_END } from "@/content/beyond";
import { OPENING_END, OPENING_GATE_PROGRESS, openingGateGlobal } from "@/content/opening";
import { ENGINEER_END } from "@/content/engineer";
import { ORIGIN_END } from "@/content/origin";
import { SOFTWARE_END } from "@/content/software";
import { CALL_END } from "@/content/the-call";
import { UNCERTAINTY_END } from "@/content/uncertainty";
import { WRITING_END } from "@/content/writing";
import type { JourneyDefinition, JourneyScene } from "@/engine/types";

const openingScenesLocal: JourneyScene[] = [
  {
    id: "opening",
    slug: "opening",
    title: "Opening",
    chapter: "Opening",
    environment: "dark",
    progressStart: 0,
    progressEnd: 0.075,
    camera: [
      { at: 0, state: { scale: 1, y: 0 } },
      { at: 1, state: { scale: 1.02, y: -6 } },
    ],
    transition: { type: "hold", durationMs: 0 },
  },
  {
    id: "name-reveal",
    slug: "name-reveal",
    title: "Names",
    chapter: "Opening",
    environment: "dark",
    progressStart: 0.075,
    progressEnd: 0.565,
    camera: [
      { at: 0, state: { scale: 1.01, y: -4 } },
      { at: 1, state: { scale: 1.03, y: -10 } },
    ],
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "question",
    slug: "question",
    title: "The Question",
    chapter: "Opening",
    environment: "dark",
    progressStart: 0.565,
    progressEnd: 0.668,
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "invitation",
    slug: "invitation",
    title: "Invitation",
    chapter: "Opening",
    environment: "dark",
    progressStart: 0.668,
    progressEnd: 0.742,
    transition: { type: "fade", durationMs: 600 },
  },
  {
    id: "begin",
    slug: "begin",
    title: "Begin",
    chapter: "Opening",
    environment: "dark",
    progressStart: 0.742,
    progressEnd: OPENING_GATE_PROGRESS + 0.004,
    transition: { type: "hold", durationMs: 0 },
  },
  {
    id: "brand-reveal",
    slug: "brand-reveal",
    title: "KNOWBEYONDME",
    chapter: "Opening",
    environment: "dark",
    progressStart: OPENING_GATE_PROGRESS + 0.004,
    progressEnd: 0.888,
    camera: [
      { at: 0, state: { scale: 1.02, y: 8 } },
      { at: 1, state: { scale: 1, y: 0 } },
    ],
    transition: { type: "fade", durationMs: 900 },
  },
  {
    id: "journey-intro",
    slug: "journey-intro",
    title: "The Journey",
    chapter: "Opening",
    environment: "dark",
    progressStart: 0.888,
    progressEnd: 0.968,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "origin-threshold",
    slug: "origin-threshold",
    title: "The Origin",
    chapter: "Opening",
    environment: "dark",
    progressStart: 0.968,
    progressEnd: 1,
    transition: { type: "hold", durationMs: 0 },
  },
];

const originScenesLocal: JourneyScene[] = [
  {
    id: "origin-arrive",
    slug: "origin-arrive",
    title: "The Origin",
    chapter: "Origin",
    environment: "warm",
    progressStart: 0,
    progressEnd: 0.1,
    camera: [
      { at: 0, state: { x: 12, scale: 1.02 } },
      { at: 1, state: { x: 0, scale: 1 } },
    ],
    transition: { type: "fade", durationMs: 900 },
  },
  {
    id: "origin-2015",
    slug: "origin-2015",
    title: "2015",
    chapter: "Origin",
    environment: "warm",
    progressStart: 0.1,
    progressEnd: 0.32,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "origin-2018",
    slug: "origin-2018",
    title: "2018",
    chapter: "Origin",
    environment: "technical",
    progressStart: 0.32,
    progressEnd: 0.54,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "origin-2021",
    slug: "origin-2021",
    title: "2021",
    chapter: "Origin",
    environment: "technical",
    progressStart: 0.54,
    progressEnd: 0.74,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "origin-road",
    slug: "origin-road",
    title: "The Road",
    chapter: "Origin",
    environment: "dark",
    progressStart: 0.74,
    progressEnd: 1,
    transition: { type: "hold", durationMs: 0 },
  },
];

const uncertaintyScenesLocal: JourneyScene[] = [
  {
    id: "uncertainty-road",
    slug: "uncertainty-road",
    title: "The Expected Road",
    chapter: "Uncertainty",
    environment: "dark",
    progressStart: 0,
    progressEnd: 0.16,
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "uncertainty-time",
    slug: "uncertainty-time",
    title: "Time",
    chapter: "Uncertainty",
    environment: "dark",
    progressStart: 0.16,
    progressEnd: 0.38,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "uncertainty-search",
    slug: "uncertainty-search",
    title: "Searching",
    chapter: "Uncertainty",
    environment: "dark",
    progressStart: 0.38,
    progressEnd: 0.54,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "uncertainty-sap",
    slug: "uncertainty-sap",
    title: "SAP MM",
    chapter: "Uncertainty",
    environment: "technical",
    progressStart: 0.54,
    progressEnd: 0.66,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "uncertainty-crossroads",
    slug: "uncertainty-crossroads",
    title: "Crossroads",
    chapter: "Uncertainty",
    environment: "dark",
    progressStart: 0.66,
    progressEnd: 0.84,
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "uncertainty-call",
    slug: "uncertainty-call",
    title: "The Call",
    chapter: "Uncertainty",
    environment: "dark",
    progressStart: 0.84,
    progressEnd: 1,
    transition: { type: "hold", durationMs: 0 },
  },
];

const callScenesLocal: JourneyScene[] = [
  {
    id: "call-ring",
    slug: "call-ring",
    title: "The Call",
    chapter: "The Call",
    environment: "dark",
    progressStart: 0,
    progressEnd: 0.1,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "call-options",
    slug: "call-options",
    title: "Two Options",
    chapter: "The Call",
    environment: "dark",
    progressStart: 0.1,
    progressEnd: 0.42,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "call-counsel",
    slug: "call-counsel",
    title: "Choose Completely",
    chapter: "The Call",
    environment: "dark",
    progressStart: 0.42,
    progressEnd: 0.62,
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "call-night",
    slug: "call-night",
    title: "Night",
    chapter: "The Call",
    environment: "dark",
    progressStart: 0.62,
    progressEnd: 0.7,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "call-verse",
    slug: "call-verse",
    title: "Surah Al-Baqarah 2:216",
    chapter: "The Call",
    environment: "dark",
    progressStart: 0.7,
    progressEnd: 0.78,
    transition: { type: "hold", durationMs: 0 },
  },
  {
    id: "call-quiet",
    slug: "call-quiet",
    title: "Quiet",
    chapter: "The Call",
    environment: "dark",
    progressStart: 0.78,
    progressEnd: 0.92,
    transition: { type: "fade", durationMs: 900 },
  },
  {
    id: "call-morning",
    slug: "call-morning",
    title: "Morning",
    chapter: "The Call",
    environment: "warm",
    progressStart: 0.92,
    progressEnd: 0.95,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "call-decision",
    slug: "call-decision",
    title: "The Second Road",
    chapter: "The Call",
    environment: "technical",
    progressStart: 0.95,
    progressEnd: 1,
    transition: { type: "hold", durationMs: 0 },
  },
];

const softwareScenesLocal: JourneyScene[] = [
  {
    id: "software-transform",
    slug: "software-transform",
    title: "Transformation",
    chapter: "Software",
    environment: "technical",
    progressStart: 0,
    progressEnd: 0.18,
    camera: [
      { at: 0, state: { scale: 1, y: 4 } },
      { at: 1, state: { scale: 1.03, y: 0 } },
    ],
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "software-unknown",
    slug: "software-unknown",
    title: "The Unknown",
    chapter: "Software",
    environment: "dark",
    progressStart: 0.18,
    progressEnd: 0.32,
    camera: [
      { at: 0, state: { scale: 1.04, y: -4 } },
      { at: 1, state: { scale: 1.06, y: -8 } },
    ],
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "software-pattern",
    slug: "software-pattern",
    title: "Patterns",
    chapter: "Software",
    environment: "technical",
    progressStart: 0.32,
    progressEnd: 0.44,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "software-learning",
    slug: "software-learning",
    title: "Learning",
    chapter: "Software",
    environment: "technical",
    progressStart: 0.44,
    progressEnd: 0.62,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "software-building",
    slug: "software-building",
    title: "Building",
    chapter: "Software",
    environment: "technical",
    progressStart: 0.62,
    progressEnd: 0.74,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "software-helping",
    slug: "software-helping",
    title: "Helping",
    chapter: "Software",
    environment: "warm",
    progressStart: 0.74,
    progressEnd: 0.88,
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "software-leading",
    slug: "software-leading",
    title: "Leading",
    chapter: "Software",
    environment: "warm",
    progressStart: 0.88,
    progressEnd: 0.97,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "software-threshold",
    slug: "software-threshold",
    title: "Threshold",
    chapter: "Software",
    environment: "technical",
    progressStart: 0.97,
    progressEnd: 1,
    transition: { type: "hold", durationMs: 0 },
  },
];

const engineerScenesLocal: JourneyScene[] = [
  {
    id: "engineer-arrive",
    slug: "engineer-arrive",
    title: "Production",
    chapter: "The Engineer",
    environment: "technical",
    progressStart: 0,
    progressEnd: 0.14,
    camera: [
      { at: 0, state: { scale: 1.02, y: 4 } },
      { at: 1, state: { scale: 1, y: 0 } },
    ],
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "engineer-colan",
    slug: "engineer-colan",
    title: "Colan Info Tech",
    chapter: "The Engineer",
    environment: "technical",
    progressStart: 0.14,
    progressEnd: 0.32,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "engineer-worlds",
    slug: "engineer-worlds",
    title: "Project Worlds",
    chapter: "The Engineer",
    environment: "technical",
    progressStart: 0.32,
    progressEnd: 0.46,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "engineer-entry",
    slug: "engineer-entry",
    title: "Entry",
    chapter: "The Engineer",
    environment: "technical",
    progressStart: 0.46,
    progressEnd: 0.64,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "engineer-inspect",
    slug: "engineer-inspect",
    title: "Architecture",
    chapter: "The Engineer",
    environment: "technical",
    progressStart: 0.64,
    progressEnd: 0.8,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "engineer-merge",
    slug: "engineer-merge",
    title: "Merge",
    chapter: "The Engineer",
    environment: "dark",
    progressStart: 0.8,
    progressEnd: 0.92,
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "engineer-threshold",
    slug: "engineer-threshold",
    title: "BEYOND THE CODE",
    chapter: "The Engineer",
    environment: "dark",
    progressStart: 0.92,
    progressEnd: 1,
    transition: { type: "hold", durationMs: 0 },
  },
];

const beyondScenesLocal: JourneyScene[] = [
  {
    id: "beyond-expand",
    slug: "beyond-expand",
    title: "Expanding",
    chapter: "Beyond the Code",
    environment: "technical",
    progressStart: 0,
    progressEnd: 0.2,
    camera: [
      { at: 0, state: { scale: 1.02, y: 2 } },
      { at: 1, state: { scale: 1, y: 0 } },
    ],
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "beyond-meaning",
    slug: "beyond-meaning",
    title: "Meaning",
    chapter: "Beyond the Code",
    environment: "warm",
    progressStart: 0.2,
    progressEnd: 0.34,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "beyond-auditorium",
    slug: "beyond-auditorium",
    title: "200+",
    chapter: "Beyond the Code",
    environment: "warm",
    progressStart: 0.34,
    progressEnd: 0.54,
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "beyond-workshops",
    slug: "beyond-workshops",
    title: "Workshops",
    chapter: "Beyond the Code",
    environment: "warm",
    progressStart: 0.54,
    progressEnd: 0.68,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "beyond-create",
    slug: "beyond-create",
    title: "Experiments",
    chapter: "Beyond the Code",
    environment: "technical",
    progressStart: 0.68,
    progressEnd: 0.8,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "beyond-imagine",
    slug: "beyond-imagine",
    title: "Imagine",
    chapter: "Beyond the Code",
    environment: "warm",
    progressStart: 0.8,
    progressEnd: 0.92,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "beyond-notebook",
    slug: "beyond-notebook",
    title: "Notebook",
    chapter: "Beyond the Code",
    environment: "warm",
    progressStart: 0.92,
    progressEnd: 1,
    transition: { type: "hold", durationMs: 0 },
  },
];

const writingScenesLocal: JourneyScene[] = [
  {
    id: "writing-desk",
    slug: "writing-desk",
    title: "The Other Side",
    chapter: "Writing",
    environment: "warm",
    progressStart: 0,
    progressEnd: 0.14,
    camera: [
      { at: 0, state: { scale: 1.02, y: 4 } },
      { at: 1, state: { scale: 1, y: 0 } },
    ],
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "writing-alfaz",
    slug: "writing-alfaz",
    title: "ALFAZ E NUHAIM",
    chapter: "Writing",
    environment: "warm",
    progressStart: 0.14,
    progressEnd: 0.3,
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "writing-kinds",
    slug: "writing-kinds",
    title: "Writing",
    chapter: "Writing",
    environment: "warm",
    progressStart: 0.3,
    progressEnd: 0.46,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "writing-between",
    slug: "writing-between",
    title: "Between the Lines",
    chapter: "Writing",
    environment: "warm",
    progressStart: 0.46,
    progressEnd: 0.58,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "writing-works",
    slug: "writing-works",
    title: "Selected Works",
    chapter: "Writing",
    environment: "warm",
    progressStart: 0.58,
    progressEnd: 0.74,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "writing-library",
    slug: "writing-library",
    title: "The Unwritten",
    chapter: "Writing",
    environment: "warm",
    progressStart: 0.74,
    progressEnd: 0.9,
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "writing-threshold",
    slug: "writing-threshold",
    title: "Threshold",
    chapter: "Writing",
    environment: "technical",
    progressStart: 0.9,
    progressEnd: 1,
    transition: { type: "hold", durationMs: 0 },
  },
];

const currentScenesLocal: JourneyScene[] = [
  {
    id: "current-doyensys",
    slug: "current-doyensys",
    title: "DOYENSYS",
    chapter: "Current",
    environment: "technical",
    progressStart: 0,
    progressEnd: 0.18,
    camera: [
      { at: 0, state: { scale: 1.02, y: 2 } },
      { at: 1, state: { scale: 1, y: 0 } },
    ],
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "current-becoming",
    slug: "current-becoming",
    title: "Still Becoming",
    chapter: "Current",
    environment: "warm",
    progressStart: 0.18,
    progressEnd: 0.32,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "current-reflection",
    slug: "current-reflection",
    title: "Reflection",
    chapter: "Current",
    environment: "dark",
    progressStart: 0.32,
    progressEnd: 0.7,
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "current-unknown",
    slug: "current-unknown",
    title: "I don't know yet.",
    chapter: "Current",
    environment: "dark",
    progressStart: 0.7,
    progressEnd: 0.84,
    transition: { type: "hold", durationMs: 0 },
  },
  {
    id: "current-names",
    slug: "current-names",
    title: "Names",
    chapter: "Current",
    environment: "dark",
    progressStart: 0.84,
    progressEnd: 0.91,
    transition: { type: "fade", durationMs: 700 },
  },
  {
    id: "current-brand",
    slug: "current-brand",
    title: "KNOWBEYONDME",
    chapter: "Current",
    environment: "dark",
    progressStart: 0.91,
    progressEnd: 0.96,
    transition: { type: "fade", durationMs: 800 },
  },
  {
    id: "current-close",
    slug: "current-close",
    title: "Journey Still Being Written",
    chapter: "Current",
    environment: "dark",
    progressStart: 0.96,
    progressEnd: 1,
    transition: { type: "hold", durationMs: 0 },
  },
];

function projectScenes(scenes: JourneyScene[], start: number, end: number): JourneyScene[] {
  const span = end - start;
  return scenes.map((scene) => ({
    ...scene,
    progressStart: start + scene.progressStart * span,
    progressEnd: start + scene.progressEnd * span,
  }));
}

export const openingJourney: JourneyDefinition = {
  id: "knowbeyondme-opening",
  title: "KNOWBEYONDME",
  mode: "journey",
  scrollLengthVh: 100,
  progressMode: "cinematic",
  hud: "hidden",
  gateProgress: openingGateGlobal(),
  autoUntilProgress: 1,
  lingerFromProgress: ORIGIN_END,
  openingEndProgress: OPENING_END,
  scenes: [
    ...projectScenes(openingScenesLocal, 0, OPENING_END),
    ...projectScenes(originScenesLocal, OPENING_END, ORIGIN_END),
    ...projectScenes(uncertaintyScenesLocal, ORIGIN_END, UNCERTAINTY_END),
    ...projectScenes(callScenesLocal, UNCERTAINTY_END, CALL_END),
    ...projectScenes(softwareScenesLocal, CALL_END, SOFTWARE_END),
    ...projectScenes(engineerScenesLocal, SOFTWARE_END, ENGINEER_END),
    ...projectScenes(beyondScenesLocal, ENGINEER_END, BEYOND_END),
    ...projectScenes(writingScenesLocal, BEYOND_END, WRITING_END),
    ...projectScenes(currentScenesLocal, WRITING_END, 1),
  ],
};
